#!/bin/bash

if [ ${1} = "self-install" ]
then



sudo cp -r ./installer /usr/bin && sudo cp -r ./installer /bin

fi

if [ ${1} = "install" ]
then

cd ..

cd ..

cd Downloads

wget https://raw.githubusercontent.com/Psylops/calculator-script/main/Build/multicalc.sh

chmod 755 multicalc.sh

mv multicalc.sh multicalc

sudo cp -r ./multicalc /bin && sudo cp -r ./multicalc /usr/bin

rm -r ./multicalc

fi

if [ ${1} = "uninstall" ]
then

sudo rm -r /bin/multicalc && sudo rm -r /usr/bin/multicalc

fi

if [ ${1} = "self-destruct" ]
then

sudo rm -r /bin/installer && sudo rm -r /usr/bin/installer

fi