#!/bin/bash

if [ ${1} = "self-install" ]
then



sudo cp -r ./installer /usr/bin && sudo cp -r ./installer /bin

fi

if [ ${1} = "install" ]
then

cd Downloads || exit

wget https://raw.githubusercontent.com/Psylops/calculator-script/main/Build/calc.sh
chmod 755 calc

sudo cp -r ./calc /bin && sudo cp -r ./calc /usr/bin

fi

if [ ${1} = "uninstall" ]
then

sudo rm -r /bin/calc && sudo rm -r /usr/bin/calc

fi

if [ ${1} = "self-destruct" ]
then

sudo rm -r /bin/installer && sudo rm -r /usr/bin/installer

fi